/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PrimeButton: typeof import('primevue/button')['default']
    PrimeCard: typeof import('primevue/card')['default']
    PrimeChip: typeof import('primevue/chip')['default']
    PrimeColumn: typeof import('primevue/column')['default']
    PrimeDataTable: typeof import('primevue/datatable')['default']
    PrimeDataView: typeof import('primevue/dataview')['default']
    PrimeFloatLabel: typeof import('primevue/floatlabel')['default']
    PrimeImage: typeof import('primevue/image')['default']
    PrimeInputText: typeof import('primevue/inputtext')['default']
    PrimeMenubar: typeof import('primevue/menubar')['default']
    PrimeMultiSelect: typeof import('primevue/multiselect')['default']
    PrimePanel: typeof import('primevue/panel')['default']
    PrimeSelect: typeof import('primevue/select')['default']
    PrimeTag: typeof import('primevue/tag')['default']
    PrimeToggleButton: typeof import('primevue/togglebutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
